### ISSUE TITLE
User XYZ already has a running server.

### ISSUE THREAD

**Issue by arnim** [mrorro/da#1]
Hi all,

I love that EGI is developing a Binder / Notebooks service. I just gave it a test and wanted to try a few repositories in a consecutive row. I ran into the problem "User XYZ already has a running server."

![image](https://user-images.githubusercontent.com/265541/153707349-e30b5c2c-cd42-4cda-a57d-c02a7ed90533.png)

How can I stop my server?

Sorry for opening the post in this repo, but I couldn't find another public and easily accessible issue tracking. If there is a public issue tracking for EGI Notebooks plz let me know.

We have a similar instance at GESIS https://notebooks.gesis.org/ and we've developed an extension enabling permanent binder import https://github.com/gesiscss/persistent_binderhub for JupyterHub.

Since we are primarily a social science institute we would love if there would be a comparable service on the EGI/EOSC level.
I also shared the link to your service in the [mybinder.org-deploy chat](https://gitter.im/jupyterhub/mybinder.org-deploy), I hope you don't mind :) 

Best
Arnim

**Comment by arnim** [comment]
cc @enolfc

**Comment by enolfc** [comment]
Thanks for reporting this! The hub is available at https://binder.notebooks.egi.eu/hub/hub/home, there you should be able to handle your existing server. 
We certainly need a better way to handle this. I have opened a issue for that in our internal repo. The persistent_binderhub looks very interesting, will check it with detail

**Comment by mrorro** [comment]
You need to shutdown or logout from the notebook. If you closed your tab and didn't save the token I'm afraid that at the moment there is no way to access again the notebook and close it. It'll stop automatically after sometime of inactivity.

**Comment by arnim** [comment]
@enolfc Thank you for your quick feedback ;)

I really like the EGI Notebooks / Binder system you are building. At the time we started notebooks.gesis.org nothing comparable was available at a European level. In the best case, we could constructively dissolve our Jupyter service at GESIS and build on EGI offerings. This might be also interesting for other service providers in the computational sciences (cc @fangohr). To get there, I think it would be necessary to think about

- scalability, number of users, and resources per user (i.e. HPCish, GPUs ...)
- on-site data access 
- Simplified AAI
- potential mybinder.org federation membership for a European deployment

Let me know if there is anything we can do ;)

Best
Arnim
